name: Python CI Example

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python V3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unittests
      run: |
        python -m unittest discover -v
      continue-on-error: true
       
    - name: Run coverage
      run: |
        coverage run -m unittest discover
        coverage report -m 
        coverage json -o coverage.json
      continue-on-error: true

    - name: Run type checker
      run: mypy source
      continue-on-error: true

    - name: Run static code analysis
      run: pylint main.py source tests

    - name: Parse coverage results
      id: coverage
      run: |
        COVERAGE_PERCENT=$(python -c "import json; print(round(json.load(open('coverage.json'))['totals']['percent_covered'], 2))")
        echo "coverage=${COVERAGE_PERCENT}" >> $GITHUB_ENV

    - name: Parse pylint results
      id: pylint
      run: |
        PYLINT_SCORE=$(pylint --output-format=parseable main.py source tests | grep -oP 'Your code has been rated at \K[^/]+')
        echo "pylint_score=${PYLINT_SCORE}" >> $GITHUB_ENV
  
    - name: Create coverage badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: d506acc54dead9ca1d070488e813d253
        filename: coverage.json 
        label: Coverage
        message: ${{ env.coverage }}%
        valColorRange: ${{ env.coverage }}%
        minColorRange: 50
        maxColorRange: 90

    - name: Create pylint badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: d506acc54dead9ca1d070488e813d253
        filename: pylint-score.json 
        label: Pylint Score
        message: ${{ env.pylint_score }}
        valColorRange: ${{ env.pylint_score }}
        minColorRange: 5
        maxColorRange: 9
