name: Python CI Example

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python V3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unittests
      run: |
        python -m unittest discover -v
       
    - name: Run coverage
      run: |
        coverage run -m unittest discover
        coverage report -m 
        coverage json -o coverage.json

    - name: Run static code analysis
      run: pylint main.py source tests

    - name: Parse coverage results
      id: coverage
      run: |
        COVERAGE_PERCENT=$(python -c "import json; print(json.load(open('coverage.json'))['totals']['percent_covered'])")
        echo "::set-output name=coverage::${COVERAGE_PERCENT}"

    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: d506acc54dead9ca1d070488e813d253
        filename: coverage.json 
        label: Coverage
        message: ${{ steps.coverage.outputs.coverage }}%
        color: green

    - name: Create Test Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: d506acc54dead9ca1d070488e813d253
        filename: test.json 
        label: Hello
        message: World
        color: orange
