name: Python CI Example

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python V3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unittests
      run: |
        python -m unittest discover -v
       
    - name: Run coverage
      run: |
        coverage run -m unittest discover
        coverage report -m > coverage.txt

    - name: Run static code analysis
      run: pylint main.py source tests

    - name: Extract coverage percentage
      id: extract_coverage
      run: |
        COVERAGE=$(grep -Po 'TOTAL.*?\K[\d.]+%' coverage.txt)
        echo "coverage=${COVERAGE}" >> $GITHUB_ENV

    - name: Create coverage badge
      uses: schneegans/dynamic-badges-action@v1.5.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        label: coverage
        message: ${{ env.coverage }}
        color: ${{ env.coverage >= '80%' && 'green' || 'red' }}

