name: Python CI Example

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python V3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unittests and coverage
      run: |
        python -m unittest discover -v
        coverage run -m unittest discover

    - name: Generate coverage report
      run: |
        coverage report -m > coverage_report.txt

    - name: Run static code analysis
      run: pylint source

    - name: Upload coverage and code analysis 
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: code-report
        path: |
          coverage_report.txt
