name: Python CI Example

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python V3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unittests
      run: |
        python -m unittest discover -v
       
    - name: Run coverage
      run: |
        coverage run -m unittest discover
        coverage xml
        coverage report -m  

    - name: Run static code analysis
      run: pylint main.py source tests

    - name: Generate coverage badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        coverage-xml: coverage.xml

    - name: Upload coverage badge
      uses: actions/upload-artifact@v2
      with:
        name: coverage-badge
        path: badge-line.svg
